import React,{useEffect,useRef,useState} from 'react';
import{createRoot}from'react-dom/client';
import{ArrowLeft,ArrowRight,BookOpen,Check,ChevronDown,History,Lightbulb,Mic,Pause,Send,Settings2,SkipForward,Sparkles,Volume2,VolumeX,X}from'lucide-react';
import './style.css';
const names={present:'Present',preterite:'Preterite',imperfect:'Imperfect',mixed:'Any tense'};
const shortTitles={'unit-1-0':'Life in community','unit-1-1':'Family & friends','unit-1-2':'School & learning','unit-1-3':'A bigger world'};
function Character({emotion='idle',className=''}){return <div className={`character ${className}`}><img src={`/character/${emotion}.webp?v=3`} width="640" height="720" alt={`Lucía ${emotion==='happy'?'waving happily':emotion==='talk'?'talking':emotion==='thinking'?'thinking':'smiling'}`} onError={e=>{if(!e.currentTarget.src.includes('lucia.png'))e.currentTarget.src='/character/lucia.png?v=3';}}/></div>}
function App(){
 const[data,setData]=useState(null),[view,setView]=useState('home'),[activeId,setActiveId]=useState(null),[deckId,setDeckId]=useState('unit-1-1'),[mode,setMode]=useState('vocabulary'),[tense,setTense]=useState('present');
 const[draft,setDraft]=useState(''),[pending,setPending]=useState(false),[error,setError]=useState(''),[emotion,setEmotion]=useState('idle'),[muted,setMuted]=useState(true),[translated,setTranslated]=useState(false),[hint,setHint]=useState(false),[meaning,setMeaning]=useState(false),[listening,setListening]=useState(false),[dialog,setDialog]=useState(null),[search,setSearch]=useState('');
 const timer=useRef(),rec=useRef(),textarea=useRef(),request=useRef(null),soundEpoch=useRef(0),token=useRef('');
 const session=data?.sessions.find(s=>s.id===activeId),deck=data?.unit.decks.find(d=>d.id===(view==='play'?session?.deckId:deckId));
 const last=session?.messages.filter(m=>m.role==='assistant').at(-1);
 const goal=session?.goal;
 const totalXp=data?.sessions.reduce((n,s)=>n+s.xp,0)||0;
 const lastResult=last?.score?.goalMet!==undefined?last:null;
 useEffect(()=>{fetch('/api/state').then(r=>{if(!r.ok)throw Error('Couldn’t load Habla. Refresh to try again.');return r.json();}).then(d=>{token.current=d.token;setData(d);}).catch(e=>setError(e.message));return()=>{clearTimeout(timer.current);rec.current?.abort();window.speechSynthesis?.cancel();};},[]);
 useEffect(()=>{window.scrollTo({top:0,behavior:'instant'});},[view,activeId]);
 useEffect(()=>{if(dialog){const el=document.querySelector('dialog');el.showModal();return()=>el.close();}},[dialog]);
 useEffect(()=>{const ctx=document.modelContext;if(!ctx?.registerTool||!data)return;const lifecycle=new AbortController();const tools=[{name:'get_spanish_practice_state',description:'Read deck and saved practice summaries.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true},execute:()=>({decks:data.unit.decks.map(d=>({id:d.id,title:d.title,words:d.terms.length})),sessions:data.sessions.map(s=>({id:s.id,title:s.title,turns:s.turns,complete:s.complete})),goal:session?.goal||null})},{name:'open_saved_spanish_conversation',description:'Open a saved conversation without sending a sentence.',inputSchema:{type:'object',properties:{sessionId:{type:'string'}},required:['sessionId'],additionalProperties:false},annotations:{readOnlyHint:false},execute:async(input)=>{if(pending)throw Error('A reply is pending');const s=data.sessions.find(s=>s.id===input.sessionId);if(!s)throw Error('Unknown conversation');resume(s);await new Promise(r=>requestAnimationFrame(()=>requestAnimationFrame(r)));return {id:s.id,goal:s.goal};}}];for(const t of tools)try{Promise.resolve(ctx.registerTool(t,{signal:lifecycle.signal})).catch(()=>{});}catch{}return()=>lifecycle.abort();},[data,pending,activeId]);
 async function api(route,body,retry=true){const r=await fetch(route,{method:'POST',headers:{'Content-Type':'application/json','X-Habla-Token':token.current},body:JSON.stringify(body)});const out=await r.json();if(r.status===403&&retry){const fresh=await fetch('/api/state').then(r=>r.json());token.current=fresh.token;return api(route,body,false);}if(!r.ok)throw Error(out.error||'Couldn’t connect. Try again.');return out;}
 function update(s,progress){setData(d=>({...d,progress:progress||d.progress,sessions:[s,...d.sessions.filter(x=>x.id!==s.id)]}));}
 function stopSound(){soundEpoch.current++;clearTimeout(timer.current);window.speechSynthesis?.cancel();setEmotion('idle');}
 function say(text,force=false){clearTimeout(timer.current);if((muted&&!force)||!window.speechSynthesis){setEmotion('talk');timer.current=setTimeout(()=>setEmotion('idle'),Math.min(6000,Math.max(1800,text.length*40)));return;}window.speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(text);u.lang='es-MX';u.rate=.92;const voices=window.speechSynthesis.getVoices();u.voice=voices.find(v=>v.lang==='es-MX')||voices.find(v=>v.lang.startsWith('es'))||null;u.onstart=()=>setEmotion('talk');u.onend=()=>setEmotion('idle');u.onerror=()=>setEmotion('idle');window.speechSynthesis.speak(u);}
 function celebrate(text){clearTimeout(timer.current);setEmotion('happy');const epoch=soundEpoch.current;timer.current=setTimeout(()=>{if(epoch===soundEpoch.current)say(text);},1800);}
 function home(){if(pending)return;stopSound();rec.current?.abort();setView('home');setError('');setDialog(null);}
 function resume(s){if(pending)return;stopSound();if(s.id!==activeId)setDraft('');setActiveId(s.id);setView('play');setHint(false);setMeaning(false);setTranslated(false);setDialog(null);setError('');if(s.complete)setEmotion('happy');}
 async function start(){if(pending)return;setPending(true);setError('');try{const out=await api('/api/sessions',{deckId,mode,tense});update(out.session);setActiveId(out.session.id);setView('play');setDraft('');setHint(false);setMeaning(false);setTranslated(false);say(out.session.messages[0].text);}catch(e){setError(e.message);}finally{setPending(false);}}
 async function submit(e){e?.preventDefault();if(pending||!draft.trim()||session.complete)return;const text=draft.trim();setPending(true);setError('');stopSound();setEmotion('thinking');if(!request.current||request.current.text!==text||request.current.sessionId!==session.id)request.current={sessionId:session.id,text,requestId:crypto.randomUUID()};try{const out=await api('/api/turn',request.current);update(out.session,out.progress);setDraft('');request.current=null;setHint(false);setMeaning(false);setTranslated(false);if(out.result.score.goalMet)celebrate(out.result.reply);else say(out.result.reply);}catch(e){setError(e.message);setEmotion('idle');}finally{setPending(false);textarea.current?.focus();}}
 async function skip(){if(pending)return;setPending(true);setError('');try{const out=await api('/api/skip',{sessionId:session.id});update(out.session,out.progress);setHint(false);setMeaning(false);setDraft('');say(out.session.messages.at(-1).text);}catch(e){setError(e.message);}finally{setPending(false);}}
 function voice(){if(listening){rec.current?.stop();return;}const SR=window.SpeechRecognition||window.webkitSpeechRecognition;if(!SR){setError('Voice works in Chrome. You can keep typing here.');return;}stopSound();const r=new SR();rec.current=r;r.lang='es-MX';r.interimResults=true;r.continuous=false;const prefix=draft;r.onstart=()=>{setListening(true);setError('');};r.onresult=e=>setDraft((prefix+' '+Array.from(e.results).map(x=>x[0].transcript).join(' ')).trim().slice(0,1200));r.onend=()=>setListening(false);r.onerror=e=>{setListening(false);setError(e.error==='not-allowed'?'Microphone access is off. You can type instead.':'Didn’t catch that. Try again or type.');};r.start();}
 if(!data)return <div className="loading"><span className="brand">habla<span>!</span></span><p>{error||'Un momentito…'}</p>{error&&<button onClick={()=>location.reload()}>Refresh</button>}</div>;
 return <div className="app"><header className="site-header"><button className="brand" onClick={home} disabled={pending} aria-label="Habla home">habla<span>!</span></button><nav><button className="nav-button" disabled={pending} onClick={()=>setDialog('chats')}><History size={19}/><span>Your chats</span></button><span className="xp-pill"><Sparkles size={16}/>{totalXp}<span>XP</span></span></nav></header>
 {error&&<div className="error" role="alert"><span>{error}</span><button aria-label="Dismiss error" onClick={()=>setError('')}><X size={18}/></button></div>}
 {view==='home'?<main className="home-page"><section className="home-copy"><span className="eyebrow">A LITTLE SPANISH, EVERY DAY</span><h1>What shall we<br/><em>talk about?</em></h1><div className="deck-choices" aria-label="Choose a vocabulary deck">{data.unit.decks.map(d=><button className={`deck-choice ${d.id===deckId?'selected':''}`} key={d.id} onClick={()=>setDeckId(d.id)} aria-pressed={d.id===deckId}><span className={`deck-index index-${d.number.replace('.','')}`}>{d.number}</span><span><strong>{shortTitles[d.id]||d.title}</strong><small>{d.terms.length} words</small></span><span className="selection-check">{d.id===deckId?<Check size={16}/>:<ArrowRight size={17}/>}</span></button>)}</div><div className="practice-options"><div className="mode-switch" aria-label="Practice focus"><button className={mode==='vocabulary'?'active':''} onClick={()=>setMode('vocabulary')} aria-pressed={mode==='vocabulary'}>Words & phrases</button><button className={mode==='tense'?'active':''} onClick={()=>setMode('tense')} aria-pressed={mode==='tense'}>Tenses</button></div>{mode==='tense'&&<label className="tense-select"><span className="sr-only">Choose tense</span><select value={tense} onChange={e=>setTense(e.target.value)}>{Object.entries(names).map(([k,v])=><option key={k} value={k}>{v}</option>)}</select><ChevronDown size={15}/></label>}</div><button className="primary start-button" onClick={start} disabled={pending}>{pending?'Getting ready…':'Let’s talk'}<ArrowRight size={22}/></button><div className="home-links"><button onClick={()=>setDialog('words')}>Peek at the words <BookOpen size={15}/></button><span>One sentence at a time.</span></div>{data.sessions.some(s=>!s.complete)&&<button className="resume-link" disabled={pending} onClick={()=>resume(data.sessions.find(s=>!s.complete))}><History size={15}/> Continue your last chat <ArrowRight size={16}/></button>}</section><section className="home-character" aria-label="Meet Lucía"><div className="hello-note">¡Hola, soy Lucía!<span>✦</span></div><Character emotion={emotion}/></section></main>:session&&goal?<main className="practice-page"><div className="practice-toolbar"><button className="back-button" onClick={home} disabled={pending}><ArrowLeft size={18}/><span>{shortTitles[session.deckId]||session.title}</span></button><div className="round-dots" aria-label={`${session.turns} of 6 goals completed`}>{Array.from({length:6},(_,i)=><span key={i} className={i<session.turns?'done':i===session.turns?'current':''}>{i<session.turns?<Check size={11}/>:null}</span>)}</div><button className="icon-button" onClick={()=>{setMuted(!muted);if(!muted)stopSound();}} aria-label={muted?'Turn voice on':'Turn voice off'} title={muted?'Voice off':'Voice on'}>{muted?<VolumeX size={19}/>:<Volume2 size={19}/>}</button></div>
 <section className={`practice-stage ${session.complete?'finished':''}`}><div className="dialogue"><div className="lucia-name"><span/> LUCÍA <button className="listen-button" aria-label="Listen to Lucía" onClick={()=>say(last.text,true)} disabled={pending}><Volume2 size={16}/></button></div>{session.complete?<><h1>¡Lo hiciste!</h1><p className="finish-copy">Six little wins. <b>{session.xp} XP.</b></p><button className="primary" disabled={pending} onClick={()=>{setDeckId(session.deckId);setMode(session.mode);setTense(session.tense);setView('home');}}>Keep talking <ArrowRight size={20}/></button><button className="understated" onClick={()=>setDialog('history')}>Look back at your sentences</button></>:<><h1 className={pending?'thinking-text':''} lang="es" aria-live="polite">{pending?'A ver…':last.text}</h1>{translated&&!pending&&<p className="translation">{last.translation}</p>}<button className="translate-button" onClick={()=>setTranslated(!translated)} disabled={pending}>{translated?'Hide English':'Translate'}</button><div className="single-goal"><span>{goal.kind==='word'?'TRY USING':'SAY IT IN'}</span><button className="goal-word" lang="es" onClick={()=>setMeaning(!meaning)} aria-label={`Goal: ${goal.label}. Show meaning.`}>{goal.label}<span className="meaning-mark">?</span></button>{meaning&&<p>{goal.meaning}</p>}</div></>}</div><div className="practice-character"><Character emotion={session.complete?'happy':emotion}/></div>{lastResult&&!pending&&!session.complete&&<div className={`result-toast ${lastResult.score.goalMet?'success':'nudge'}`} role="status">{lastResult.score.goalMet?<><Check size={17}/><span>{lastResult.goal?.label||'¡Bien hecho!'}</span><b>+20</b></>:<><Lightbulb size={17}/><span>{lastResult.feedback}</span></>}</div>}</section>
 {!session.complete&&<form className="reply-form" onSubmit={submit}><label htmlFor="reply">Your turn</label><div className={`composer ${listening?'is-listening':''}`}><button type="button" className="mic-button" onClick={voice} disabled={pending} aria-label={listening?'Stop listening':'Use microphone'} title="Use your microphone">{listening?<Pause size={20}/>:<Mic size={20}/>}</button><textarea id="reply" ref={textarea} value={draft} onChange={e=>setDraft(e.target.value)} placeholder={listening?'Listening…':'Una frase…'} maxLength={1200} rows={1} disabled={pending} onKeyDown={e=>{if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();submit();}}}/><button type="submit" className="send-button" disabled={!draft.trim()||pending} aria-label="Send sentence">{pending?<span className="spinner"/>:<ArrowRight size={23}/>}</button></div><div className="reply-tools"><button type="button" className={hint?'hint-active':''} onClick={()=>setHint(!hint)}><Lightbulb size={16}/>{hint?'Hide hint':'A little help'}</button><span>{listening?'Review your words, then send.':'Enter ↵'}</span><button type="button" onClick={()=>setDialog('history')} aria-label="Conversation history"><History size={17}/></button></div>{hint&&<div className="hint-panel"><p>{goal.kind==='word'?goal.meaning:goal.meaning+'.'}<span>{goal.kind==='tense'?(goal.tense==='preterite'?'Ayer, yo…':goal.tense==='imperfect'?'Cuando era pequeño/a…':'Normalmente, yo…'):'A short sentence is enough.'}</span></p>{goal.kind==='word'&&<button type="button" disabled={pending} onClick={skip}>Another word <SkipForward size={14}/></button>}</div>}</form>}
 </main>:<main className="loading"><p>Reconnecting your chat…</p><button onClick={()=>location.reload()}>Refresh</button></main>}
 {view==='home'&&<footer><span>Unit 1 · 85 words</span><button onClick={()=>setDialog('about')}>About Habla</button></footer>}
 {dialog&&<dialog aria-label={dialog==='chats'?'Your conversations':dialog==='words'?'Vocabulary':dialog==='history'?'Conversation history':'About Habla'} onCancel={()=>setDialog(null)} onClick={e=>{if(e.target===e.currentTarget)setDialog(null);}}><div className="dialog-top"><span className="eyebrow">HABLA</span><button className="icon-button" onClick={()=>setDialog(null)} aria-label="Close"><X size={21}/></button></div>{dialog==='chats'&&<><h2>Your chats.</h2>{data.sessions.length?<div className="chat-list">{data.sessions.map(s=><button key={s.id} disabled={pending} onClick={()=>resume(s)}><span className="chat-thumb"><img src="/character/lucia.png?v=3" alt=""/></span><span><strong>{shortTitles[s.deckId]||s.title}</strong><small>{s.complete?'Round complete':`${s.turns}/6 wins`} · {s.mode==='tense'?names[s.tense]:'Words & phrases'}</small></span><ArrowRight size={18}/></button>)}</div>:<div className="empty"><p>Your first “hola” is waiting.</p><button className="primary" onClick={()=>{setDialog(null);home();}}>Pick a deck <ArrowRight size={18}/></button></div>}</>}{dialog==='words'&&<><h2>{shortTitles[deck.id]||deck.title}</h2><label className="search-label"><span className="sr-only">Find a word</span><input placeholder="Find a word…" value={search} onChange={e=>setSearch(e.target.value)}/></label><div className="word-list">{deck.terms.filter(t=>(t.es+' '+t.en).toLowerCase().includes(search.toLowerCase())).map(t=><div key={t.id}><strong lang="es">{t.es}</strong><span>{t.en}</span></div>)}</div><a className="source-link" href={deck.sourceUrl} target="_blank" rel="noreferrer">Original Quizlet deck ↗</a></>}{dialog==='history'&&<><h2>Your conversation.</h2><div className="history">{session.messages.map((m,i)=><article key={i} className={m.role}><small>{m.role==='assistant'?'Lucía':'You'}</small><p lang="es">{m.text}</p>{m.feedback&&<span>{m.feedback}</span>}</article>)}</div></>}{dialog==='about'&&<><h2>One sentence is a start.</h2><div className="about-copy"><p>Use the word or tense on screen. That’s the whole goal. A natural sentence earns 20 XP; a miss gets a gentle nudge and another try.</p><p>Six wins finish a round. Words that need work return sooner.</p><p>Your chats stay on this computer. Sentences go to your configured AI tutor, whose feedback can make mistakes.</p><p>Voice dictation uses your browser’s speech service. You always review the transcript before sending.</p><p className="small">Unit 1 · Las familias en diferentes sociedades<br/>85 entries from four Quizlet sets. Original Blender character.</p></div></>}</dialog>}
 </div>
}
createRoot(document.getElementById('root')).render(<App/>);
