import React, { useState, useEffect, useRef } from 'react';
import {createRoot} from 'react-dom/client';
import {Home, Layers, MessageCircle, ArrowUpRight, ArrowRight, ArrowLeft, Plus, Sparkles, Flame, Check, X, Volume2, VolumeX, Mic, Send, BookOpen, Users, Globe, School, Trophy, Target, RotateCcw, ChevronRight, Lightbulb, Pause, Clock, Star, CheckCircle2, HelpCircle} from 'lucide-react';
import './style.css';
const tenseNames={present:'Present',preterite:'Preterite',imperfect:'Imperfect',mixed:'Mix it up'};
 function Character({home=false,emotion}){return <div className={`character ${home?'character-home':''}`}><img src={`/character/${emotion}.webp`} onError={e=>{if(!e.currentTarget.src.endsWith('/lucia.png'))e.currentTarget.src='/character/lucia.png';}} alt={`Lucía, your friendly 3D Spanish conversation partner, ${emotion==='happy'?'celebrating':emotion==='talk'?'talking':'smiling'}`} width="600" height="720"/><span className="character-label"><span/> LUCÍA <span className="label-light">your conversation amiga</span></span></div>}
function App(){
 const [data,setData]=useState(null),[view,setView]=useState('home'),[activeId,setActiveId]=useState(null),[deckId,setDeckId]=useState('unit-1-0'),[tense,setTense]=useState('present'),[draft,setDraft]=useState(''),[pending,setPending]=useState(false),[error,setError]=useState(''),[emotion,setEmotion]=useState('idle'),[muted,setMuted]=useState(true),[translation,setTranslation]=useState(false),[hint,setHint]=useState(false),[revealed,setRevealed]=useState({}),[listening,setListening]=useState(false),[dialog,setDialog]=useState(null),[query,setQuery]=useState('');
 const textarea=useRef(),recognition=useRef(),animationTimer=useRef(),requestRef=useRef(null);
 const session=data?.sessions.find(s=>s.id===activeId), deck=data?.unit.decks.find(d=>d.id===(session?.deckId||deckId));
 const last=session?.messages.filter(m=>m.role==='assistant').at(-1);
 useEffect(()=>{fetch('/api/state').then(r=>{if(!r.ok)throw Error('Cannot load the game.');return r.json()}).then(setData).catch(e=>setError(e.message));return()=>{clearTimeout(animationTimer.current);recognition.current?.abort();window.speechSynthesis?.cancel();}},[]);
 useEffect(()=>{window.scrollTo({top:0,behavior:'instant'});},[view,activeId]);
 useEffect(()=>{if(!dialog)return;const el=document.querySelector('dialog');el?.showModal();return()=>el?.close();},[dialog]);
 async function api(url,body){const r=await fetch(url,{method:'POST',headers:{'Content-Type':'application/json','X-Habla-Token':data.token},body:JSON.stringify(body)});const out=await r.json();if(!r.ok)throw Error(out.error||'Something went wrong.');return out;}
 function updateSession(s,progress){setData(d=>({...d,progress:progress||d.progress,sessions:[s,...d.sessions.filter(x=>x.id!==s.id)]}));}
 function animate(state,duration=2500){clearTimeout(animationTimer.current);setEmotion(state);animationTimer.current=setTimeout(()=>setEmotion('idle'),duration);}
 function say(text,force=false){clearTimeout(animationTimer.current);if((muted&&!force)||!window.speechSynthesis){animate('talk',Math.min(7000,text.length*45));return;}window.speechSynthesis.cancel();const utter=new SpeechSynthesisUtterance(text);utter.lang='es-MX';utter.rate=.9;const voices=window.speechSynthesis.getVoices();utter.voice=voices.find(v=>v.lang==='es-MX')||voices.find(v=>v.lang.startsWith('es'))||null;utter.onstart=()=>setEmotion('talk');utter.onend=()=>setEmotion('idle');utter.onerror=()=>setEmotion('idle');window.speechSynthesis.speak(utter);}
 async function start(id=deckId){if(pending)return;setPending(true);setError('');try{const {session:s}=await api('/api/sessions',{deckId:id,tense});updateSession(s);setActiveId(s.id);setView('play');setDraft('');setTranslation(false);setHint(false);setRevealed({});say(s.messages[0].text);}catch(e){setError(e.message);}finally{setPending(false);}}
 function resume(s){if(pending)return;setActiveId(s.id);setView('play');setDraft('');setHint(false);setTranslation(false);setError('');setEmotion('idle');}
 async function submit(e){e?.preventDefault();if(!draft.trim()||pending||session.complete)return;const text=draft.trim();setPending(true);setError('');window.speechSynthesis?.cancel();setEmotion('thinking');if(!requestRef.current||requestRef.current.text!==text||requestRef.current.sessionId!==session.id)requestRef.current={text,sessionId:session.id,requestId:crypto.randomUUID()};try{const out=await api('/api/turn',requestRef.current);updateSession(out.session,out.progress);setDraft('');requestRef.current=null;setHint(false);setTranslation(false);setRevealed({});if(out.result.score.total>0){clearTimeout(animationTimer.current);setEmotion('happy');animationTimer.current=setTimeout(()=>say(out.result.reply),1400);}else say(out.result.reply);}catch(e){setError(e.message);setEmotion('idle');}finally{setPending(false);textarea.current?.focus();}}
 function voice(){if(listening){recognition.current?.stop();return;}const SR=window.SpeechRecognition||window.webkitSpeechRecognition;if(!SR){setError('Voice input isn’t supported in this browser. You can keep typing, or open Habla in Chrome.');return;}const rec=new SR();recognition.current=rec;rec.lang='es-MX';rec.interimResults=true;rec.continuous=false;let original=draft;rec.onresult=e=>{const transcript=Array.from(e.results).map(r=>r[0].transcript).join(' ');setDraft((original+' '+transcript).trim().slice(0,1200));};rec.onstart=()=>{setListening(true);setError('');};rec.onend=()=>setListening(false);rec.onerror=e=>{setListening(false);setError(e.error==='not-allowed'?'Microphone access was denied. You can type your answer instead.':'Voice input stopped. Try again or type your answer.');};rec.start();}
 async function changeScene(scene){if(pending)return;try{const {session:s}=await api('/api/scene',{sessionId:session.id,scene});updateSession(s);animate('happy',1600);}catch(e){setError(e.message);}}
 useEffect(()=>{const ctx=document.modelContext;if(!ctx?.registerTool||!data)return;const lifecycle=new AbortController();const tools=[{name:'get_spanish_practice_state',description:'Read available Spanish decks, progress, and saved conversation summaries. Does not start or submit practice.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true},execute:()=>({decks:data.unit.decks.map(d=>({id:d.id,title:d.title,words:d.terms.length})),sessions:data.sessions.map(s=>({id:s.id,title:s.title,turns:s.turns,xp:s.xp,complete:s.complete}))})},{name:'open_saved_spanish_conversation',description:'Open a saved conversation in the visible interface, without submitting a reply or spending model tokens.',inputSchema:{type:'object',properties:{sessionId:{type:'string'}},required:['sessionId'],additionalProperties:false},annotations:{readOnlyHint:false},execute:async(input)=>{if(pending)throw Error('A reply is pending');const found=data.sessions.find(s=>s.id===input.sessionId);if(!found)throw Error('Unknown conversation');resume(found);await new Promise(resolve=>requestAnimationFrame(()=>requestAnimationFrame(resolve)));return {id:found.id,view:'play',turns:found.turns};}}];for(const tool of tools){try{Promise.resolve(ctx.registerTool(tool,{signal:lifecycle.signal})).catch(()=>{});}catch{}}return()=>lifecycle.abort();},[data,pending]);
 const totalXp=data?.sessions.reduce((n,s)=>n+s.xp,0)||0;
 const known=Object.values(data?.progress||{}).filter(p=>p.successes>0).length;
 const completed=data?.sessions.filter(s=>s.complete).length||0;
 const allTerms=data?.unit.decks.flatMap(d=>d.terms)||[];
 const due=allTerms.filter(t=>data?.progress[t.id]&&data.progress[t.id].dueAt<=Date.now()).length;
 function nav(v){if(pending)return;clearTimeout(animationTimer.current);setView(v);setError('');window.speechSynthesis?.cancel();recognition.current?.abort();setEmotion('idle');}

 function DeckCards(){return <div className="deck-grid">{data.unit.decks.map((d,i)=><button className={`deck-card ${d.color||'peach'} ${deckId===d.id?'selected':''}`} key={d.id} onClick={()=>{setDeckId(d.id);setDialog('deck');}}><div className="deck-top"><span className="deck-icon">{i%3===0?<Users/>:i%3===1?<School/>:<Globe/>}</span><span className="deck-number">{d.number}</span></div><h3>{d.title}</h3><p>{d.subtitle}</p><div className="deck-bottom"><span>{d.terms.length} words</span><span>{d.terms.filter(t=>data.progress[t.id]?.successes).length} practiced <ArrowUpRight size={17}/></span></div></button>)}</div>}
 if(!data)return <div className="loading"><span className="brand">habla<span>·</span></span><p>{error||'Getting your conversation ready…'}</p>{error&&<button onClick={()=>location.reload()}>Try again</button>}</div>;
 return <div className="app"><aside className="sidebar"><button className="brand" onClick={()=>nav('home')} aria-label="Habla home">habla<span>·</span></button><span className="sidebar-caption">A LITTLE SPANISH, EVERY DAY</span><nav>{[[Home,'home','Your space'],[Layers,'decks','Vocabulary decks'],[MessageCircle,'chats','Your conversations']].map(([Icon,v,label])=><button disabled={pending} key={v} className={view===v?'nav-active':''} onClick={()=>nav(v)}><Icon size={20}/><span>{label}</span>{v==='chats'&&data.sessions.length>0&&<small>{data.sessions.length}</small>}</button>)}</nav><div className="sidebar-bottom"><div className="tiny-tip"><Sparkles size={20}/><p>A little awkward?<br/><strong>That’s how learning starts.</strong></p></div><button className="how-button" onClick={()=>setDialog('help')}><HelpCircle size={18}/> How to play</button><div className="local-profile"><span>M</span><div>Your learning space<small>Saved on this computer</small></div><span className="online-dot"/></div></div></aside>
 <main className={view==='play'?'main main-play':'main'}>
 <header className="topbar"><div className="breadcrumb">{view==='play'?<><button disabled={pending} onClick={()=>nav('home')}><ArrowLeft size={16}/> Your space</button><span>/</span><span>{session?.title}</span></>:<><span className="status-dot"/> YOUR SPANISH, IN PROGRESS</>}</div><div className="topbar-right"><span className="xp-chip"><Sparkles size={15}/>{totalXp} XP</span><span className="language">ES <span>·</span> EN</span></div></header>
 {error&&<div className="error" role="alert">{error}<button onClick={()=>setError('')} aria-label="Dismiss error"><X size={16}/></button></div>}
 {view==='home'&&<div className="page home-page"><div className="page-heading"><div><span className="eyebrow">BIENVENIDO A HABLA</span><h1>A little conversation.<br/>A lot more <em>confidence.</em></h1></div><span className="hand-note">Let’s make some mistakes.<br/>The good kind. <span>↙</span></span></div>
 <section className="welcome-card"><div className="welcome-copy"><span className="pill"><span className="status-dot"/> YOUR NEXT CONVERSATION</span><h2>Come for the vocab.<br/>Stay for the charla.</h2><p>Meet Lucía. Pick a deck, find your words,<br className="desktop"/> and see where the conversation takes you.</p><div className="welcome-actions"><button className="primary" disabled={pending} onClick={()=>{const recent=data.sessions.find(s=>!s.complete);recent?resume(recent):start();}}>{data.sessions.some(s=>!s.complete)?'Pick up your conversation':'Let’s talk'} <ArrowRight size={20}/></button><span>6 replies. No pressure.</span></div></div><div className="welcome-visual"><div className="hello-bubble">¡Hola! ¿Qué tal? <span>✦</span></div><Character home emotion={emotion}/><span className="visual-sticker">Small talk.<br/><b>Big progress.</b></span></div></section>
 <div className="stats-row"><div><span className="stat-icon yellow"><Sparkles/></span><span><strong>{totalXp} <small>XP earned</small></strong><p>Every attempt counts</p></span></div><div><span className="stat-icon green"><BookOpen/></span><span><strong>{known} <small>words practiced</small></strong><p>Out of {new Set(allTerms.map(t=>t.id)).size} in your collection</p></span></div><div><span className="stat-icon coral"><MessageCircle/></span><span><strong>{completed} <small>rounds finished</small></strong><p>{due?`${due} words ready to revisit`:'One conversation at a time'}</p></span></div></div>
 <div className="section-heading"><div><span className="eyebrow">YOUR COLLECTION</span><h2>A deck for every conversation.</h2></div><button className="text-button" onClick={()=>nav('decks')}>Explore vocabulary <ArrowUpRight size={17}/></button></div><DeckCards/>
 {data.sessions.length>0&&<section className="recent"><div className="section-heading"><h2>Right where you left off.</h2><button className="text-button" onClick={()=>nav('chats')}>All conversations <ArrowRight size={16}/></button></div>{data.sessions.slice(0,2).map(s=><button className="chat-row" key={s.id} onClick={()=>resume(s)}><span className="chat-row-icon"><MessageCircle/></span><span><strong>{s.title}</strong><small>{s.turns}/6 replies · {tenseNames[s.tense]} · {new Date(s.updatedAt).toLocaleDateString()}</small></span><span className="chat-row-xp">{s.xp} XP</span><span>{s.complete?'Review':'Resume'} <ArrowRight size={17}/></span></button>)}</section>}
 <p className="source-note">UNIT 1 · LAS FAMILIAS EN DIFERENTES SOCIEDADES <span>Vocabulary adapted from your Quizlet sets.</span></p></div>}
 {view==='decks'&&<div className="page"><span className="eyebrow">MAKE THE WORDS YOURS</span><div className="page-heading"><h1>Your vocabulary decks.</h1><span className="pill">UNIT 01</span></div><p className="intro">Las familias en diferentes sociedades. Pick a deck to practice in conversation.</p><DeckCards/><div className="word-library"><div className="section-heading"><h2>A peek inside your vocabulary.</h2><input className="search" aria-label="Search vocabulary" placeholder="Find a word…" value={query} onChange={e=>setQuery(e.target.value)}/></div><div className="word-table">{allTerms.filter(t=>(t.es+' '+t.en).toLowerCase().includes(query.toLowerCase())).map((t,i)=><div key={t.id+i}><strong lang="es">{t.es}</strong><span>{t.en}</span><span className={data.progress[t.id]?.successes?'word-done':'word-new'}>{data.progress[t.id]?.successes?'Practiced':'New word'}</span></div>)}</div><p className="source-note">{data.unit.source.coverage}</p></div></div>}
 {view==='chats'&&<div className="page"><span className="eyebrow">PICK UP THE CONVERSATION</span><div className="page-heading"><h1>Your conversations.</h1><button className="primary" disabled={pending} onClick={()=>setDialog('deck')}><Plus size={18}/> New chat</button></div>{data.sessions.length?data.sessions.map(s=><button className="chat-row" key={s.id} onClick={()=>resume(s)}><span className="chat-row-icon"><MessageCircle/></span><span><strong>{s.title}</strong><small>{s.turns}/6 replies · {tenseNames[s.tense]} · {new Date(s.updatedAt).toLocaleString()}</small></span><span className="chat-row-xp">{s.xp} XP</span><span>{s.complete?'Review round':'Keep talking'} <ArrowRight size={17}/></span></button>):<div className="empty"><MessageCircle size={40}/><h2>Your first “¡hola!” is waiting.</h2><p>Start a conversation. We’ll save your place here.</p><button className="primary" onClick={()=>start()}>Meet Lucía <ArrowRight size={18}/></button></div>}</div>}
 {view==='play'&&session&&<div className="play-page"><div className="play-heading"><div><span className="eyebrow">UNIT {deck.number} · {session.complete?'ROUND COMPLETE':'LET’S HAVE A CONVERSATION'}</span><h1>{session.title}<span>.</span></h1></div><button className="sound-toggle" onClick={()=>{setMuted(!muted);if(!muted)window.speechSynthesis?.cancel();}} aria-label={muted?'Turn voice on':'Turn voice off'}>{muted?<VolumeX size={18}/>:<Volume2 size={18}/>} Voice {muted?'off':'on'}</button></div>
 <div className="game-layout"><aside className="vocab-panel"><div className="panel-title"><Layers size={17}/><span>Your word mission</span></div><p>Work these into your reply.<br/>Make them part of the story.</p><div className="target-list">{session.targets.map((id,i)=>{const t=deck.terms.find(t=>t.id===id);return <button className="target-card" key={id} onClick={()=>setRevealed(r=>({...r,[id]:!r[id]}))}><span className="target-number">0{i+1}</span><strong lang="es">{t.es}</strong><small>{revealed[id]?t.en:'Tap for a little hint'}</small><span className="target-points">+15 XP</span></button>})}</div><div className="tense-goal"><span><Target size={18}/> TENSE CHALLENGE</span><strong>{tenseNames[session.tense]}</strong><p>{session.tense==='present'?'What happens now, or usually?':session.tense==='preterite'?'What happened and finished?':session.tense==='imperfect'?'What used to happen?':'Move between now and then.'}</p><small>Use it naturally · +10 XP</small></div><button className="text-button" onClick={()=>setDialog('words')}>See the whole deck <ArrowUpRight size={15}/></button></aside>
 <section className={`scene scene-${session.scene}`} aria-label="Conversation with Lucía"><div className="scene-topline"><span className="scene-tag"><span/> {session.scene==='community'?'EN EL BARRIO':session.scene==='school'?'EN LA ESCUELA':'EN FAMILIA'}</span><span>WITH LUCÍA</span></div><div className="speech-bubble" aria-live="polite"><span className="speaker">LUCÍA <button onClick={()=>say(last.text,true)} aria-label="Listen to Lucía"><Volume2 size={15}/></button></span><p lang="es">{pending?'Un momentito… Estoy pensando.':last.text}</p>{translation&&!pending&&<p className="translation">{last.translation}</p>}<button className="translation-toggle" disabled={pending} onClick={()=>setTranslation(!translation)}>{translation?'Hide translation':'Need a translation?'}</button></div><div className="stage"><Character emotion={emotion}/><button className={`scene-prop prop-book ${session.scene==='school'?'prop-active':''}`} disabled={pending} onClick={()=>changeScene('school')} aria-label="Switch conversation to school"><img src="/character/books.png" alt=""/><span>la escuela</span><Plus size={13}/></button><button className={`scene-prop prop-family ${session.scene==='family'?'prop-active':''}`} disabled={pending} onClick={()=>changeScene('family')} aria-label="Switch conversation to family"><img src="/character/family.png" alt=""/><span>la familia</span><Plus size={13}/></button><div className="scene-caption">{pending?'Lucía is thinking…':emotion==='happy'?'¡Eso es! Keep going.':'A safe little place to try your Spanish.'}</div></div></section>
 <aside className="score-panel"><div className="panel-title"><Sparkles size={17}/> This conversation</div><div className="score-total"><span>{session.xp}</span><small>EXPERIENCE POINTS</small></div><div className="round-progress"><div><strong>Your little daily rep</strong><span>{session.turns}/6</span></div><div className="progress-track"><span style={{width:`${session.turns/6*100}%`}}/></div><small>Six replies. One step closer.</small></div>{last.score?<div className="last-score"><span className="eyebrow">LAST REPLY</span><h3>+{last.score.total} XP</h3><p><CheckCircle2 size={15}/> Vocabulary <b>+{last.score.vocabulary}</b></p><p><Target size={15}/> Tense <b>+{last.score.tense}</b></p><p><MessageCircle size={15}/> Conversation <b>+{last.score.conversation}</b></p></div>:<div className="score-guide"><Star/><h3>Find your flow.</h3><p>Use a word in context.<br/>Try a tense.<br/>Keep the story going.</p></div>}<div className="gentle-note"><span>✦</span> Mistakes are part of the conversation.</div><button className="text-button" onClick={()=>setDialog('history')}><Clock size={15}/> Conversation log</button></aside></div>
 {last.feedback&&<div className="feedback" aria-live="polite"><span className="feedback-icon"><Lightbulb size={19}/></span><div><strong>A little note from Lucía</strong><p>{last.feedback} {last.tense?.correct&&last.score?.tense>0&&<span className="tense-earned">{last.tense.name} ✓</span>}</p>{last.score?.hits.length>0&&<div className="earned-words">{last.score.hits.map(h=><span key={h.id}><Check size={11}/>{deck.terms.find(t=>t.id===h.id)?.es} <b>+15</b></span>)}</div>}</div></div>}
 {session.complete?<div className="round-complete"><span className="stat-icon yellow"><Trophy/></span><div><h2>¡Mira cuánto has hablado!</h2><p>Six replies, {session.xp} XP, and a little more confidence. Words that need practice will come back around.</p></div><button className="primary" disabled={pending} onClick={()=>start(session.deckId)}>Another little round <ArrowRight size={18}/></button></div>:<form className="composer" onSubmit={submit}><div className="composer-main"><button type="button" className={`mic-button ${listening?'listening':''}`} onClick={voice} disabled={pending} aria-label={listening?'Stop listening':'Use microphone'}>{listening?<Pause size={21}/>:<Mic size={21}/>}</button><textarea ref={textarea} aria-label="Your Spanish reply" placeholder={listening?'Listening in Spanish…':'Tu turno… write a little Spanish.'} value={draft} onChange={e=>setDraft(e.target.value)} disabled={pending} maxLength={1200} rows={2} onKeyDown={e=>{if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();submit();}}}/><button className="send-button" disabled={pending||!draft.trim()} aria-label="Send reply">{pending?<span className="spinner"/>:<ArrowRight size={24}/>}</button></div><div className="composer-footer"><button type="button" onClick={()=>setHint(!hint)}><Lightbulb size={15}/> {hint?'Hide starter':'Give me a nudge'}</button><span>{listening?'Review your transcript before sending.':'Enter to send · Shift + Enter for a new line'}</span><span>{draft.length}/1200</span></div>{hint&&<p className="starter" lang="es">{session.tense==='preterite'?'El año pasado, mi comunidad…':session.tense==='imperfect'?'Cuando era pequeño/a, nosotros…':'Desde mi punto de vista, en mi comunidad…'} <span>Finish the thought in your own words.</span></p>}<p className="voice-note">Voice input uses your browser’s speech service. You review the words before sending.</p></form>}
 </div>}
 </main>
 {dialog&&<dialog aria-label={dialog==='deck'?'Choose your conversation':dialog==='help'?'How to play':dialog==='words'?'Vocabulary list':'Conversation history'} onCancel={()=>setDialog(null)} onClick={e=>{if(e.target===e.currentTarget)setDialog(null);}}><div className="dialog-header"><span className="eyebrow">{dialog==='deck'?'MAKE IT YOUR CONVERSATION':'HABLA'}</span><button onClick={()=>setDialog(null)} aria-label="Close dialog"><X size={20}/></button></div>{dialog==='deck'&&<><h2>What shall we talk about?</h2><label className="form-label">Your deck<select value={deckId} onChange={e=>setDeckId(e.target.value)}>{data.unit.decks.map(d=><option key={d.id} value={d.id}>{d.number} · {d.title} ({d.terms.length} words)</option>)}</select></label><span className="form-label">Your tense challenge</span><div className="tense-options">{Object.entries(tenseNames).map(([v,label])=><button className={tense===v?'active':''} onClick={()=>setTense(v)} key={v}>{label}{tense===v&&<Check size={14}/>}</button>)}</div><p className="dialog-note">Three words at a time. Six replies per round. Lucía will help you find your way.</p><button className="primary full" disabled={pending} onClick={()=>{setDialog(null);start();}}>Let’s talk <ArrowRight size={18}/></button></>}{dialog==='help'&&<><h2>It starts with a little “hola.”</h2><div className="help-steps"><p><b>01 · Pick a deck.</b> Choose words you want to make your own, then a tense to practice.</p><p><b>02 · Have a conversation.</b> Reply to Lucía in your own words. Type, or use the microphone and review your transcript.</p><p><b>03 · Make the words mean something.</b> Earn 15 XP per correctly used word, 10 for the tense challenge, and 5 for a meaningful reply. Lists of keywords don’t count.</p><p><b>04 · Come back for another rep.</b> Missed words return sooner. Successful words are spaced out. A word practiced once is a start, not mastery.</p></div><p className="dialog-note">Your conversations are saved on this computer. Replies are sent to your configured AI provider for coaching; feedback can make mistakes.</p></>}{dialog==='words'&&<><h2>{deck.title}</h2><div className="modal-word-list">{deck.terms.map(t=><div key={t.id}><strong lang="es">{t.es}</strong><span>{t.en}</span>{t.note&&<small>{t.note}</small>}</div>)}</div><a className="text-button" href={deck.sourceUrl} target="_blank" rel="noreferrer">Original Quizlet deck <ArrowUpRight size={16}/></a></>}{dialog==='history'&&<><h2>Your conversation with Lucía.</h2><div className="message-history">{session.messages.map((m,i)=><article className={m.role} key={i}><small>{m.role==='assistant'?'LUCÍA':'YOU'}</small><p lang="es">{m.text}</p>{m.feedback&&<span>{m.feedback}</span>}</article>)}</div></>}</dialog>}
 </div>
}
createRoot(document.getElementById('root')).render(<App/>);
